config/routes.rb
Rails.application.routes.draw do
  root to: "dashboard#index"

  devise_for(
    :users, 
    class_name: "User", 
    path: '', 
    path_names: { 
      sign_in: 'login', 
      sign_up: 'signup', 
      sign_out: 'logout'
    },
    controllers: {
      sessions: "sessions",
      registrations: "registrations"
    }
  )

  resources :puroks
  resources :residents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purok.rb
class Purok < ApplicationRecord
  has_many :residents

  def alias
    "#{num} - #{name.titleize}"
  end
end

app/models/resident.rb
class Resident < ApplicationRecord
  belongs_to :purok

  def full_name
    last_name + ", " + first_name + " " + middle_name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, 
    :email])
    #in keys you list all the input you want to accept.
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/puroks_controller.rb
class PuroksController < ApplicationController
  protect_from_forgery except: :edit

  def index
    @purok = Purok.new
    @data = Purok.includes(:residents).order(created_at: :desc).map { |p|  [p.id, p.alias , p.residents.count, p.current_kagawad] }
  end

  def create
    @purok = Purok.new(purok_params)

    if @purok.save
      redirect_to :puroks, notice: 'Purok successfully created!'
    else
      flash[:error] = 'Purok not created.'
    end
  end

  def edit
    respond_to do |format|
      format.js do 
        @purok = Purok.find(params[:id])
      end
    end
  end

  def update
    @purok = Purok.find(params[:id])

    if @purok.update(purok_params)
      redirect_to :puroks, notice: 'Purok successfully update!'
    else
      flash[:error] = 'Purok not updated.'
    end
  end

  def destroy
    @purok = Purok.find(params[:id])
    @purok.destroy()
    redirect_to :puroks, notice: "Purok #{@purok.name} successfully deleted!"
  end

  private
    def purok_params
      params.require(:purok).permit(:id, :name, :num, :current_kagawad)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super 
  end

  protected

    def auth_options
      { scope: resource_name, recall: 'registrations#new' }
    end
  end
  

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  def index
    @data = Resident.joins(:purok).order(created_at: :desc).map { |r|  [r.id, r.full_name, r.birthdate.to_date, r.contact_no, r.purok.alias] }
  end

  def new
    @resident = Resident.new
    @purok_options = Purok.order(created_at: :desc).map { |p|  ["#{p.num} - #{p.name.titleize}", p.id] }
  end

  def create
    @resident = Resident.new(resident_params)

    if @resident.save
      redirect_to :residents, notice: 'Resident successfully created!'
    else
      flash[:error] = 'Resident not created.'
    end
  end

  def edit
    @resident = Resident.find(params[:id])
    @purok_options = Purok.order(created_at: :desc).map { |p|  ["#{p.num} - #{p.name.titleize}", p.id] }
  end

  def update
    @resident = Resident.find(params[:id])

    if @resident.update(resident_params)
      redirect_to :residents, notice: 'Resident successfully update!'
    else
      flash[:error] = 'Resident not updated.'
    end
  end

  def destroy
    @resident = Resident.find(params[:id])
    @resident.destroy()
    redirect_to :residents, notice: "Resident #{@resident.full_name} successfully deleted!"
  end

  private
    def resident_params
      params.require(:resident).permit(:id, :first_name, :last_name, :middle_name, :birthdate, :contact_no, :purok_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super 
  end

  protected

    def auth_options
      { scope: resource_name, recall: 'sessions#new' }
    end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "/assets/navbar" %>
    <%= yield :stylesheet %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= yield :javascript %>

  </head>

  <body style="padding: 20px 50px;">
    <% if user_signed_in? %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/alert" %>

    <div class="main-content" style="padding: 50px 0;">
      <%= yield %>
    </div>

    <%= yield :modal %>
  </body>
</html>

app/views/puroks/edit.js.erb
$(".modal").find(".modal-title").text("Edit Purok")
$(".modal").find("form").attr("action", "/puroks/<%=@purok.id%>")
$(".modal").find("input#purok_name").val("<%= @purok.name%>")
$(".modal").find("input#purok_num").val("<%= @purok.num%>")
$(".modal").find("input#purok_current_kagawad").val("<%= @purok.current_kagawad%>")
$(".modal form").append("<input type='hidden' name='_method' value='put' autocomplete='off'>")

$(".modal").modal()

app/views/puroks/index.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#purokModal" style="width: 80px; margin-bottom: 20px;">
  New
</button>

<table id="purok-table" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Residents</th>
      <th>Curent Kagawad</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |purok| %>
      <tr>
        <td><%= purok[1]%></td>
        <td><%= purok[2]%></td>
        <td><%= purok[3]%></td>
        <td>
          <%= link_to edit_purok_path(purok[0], format: :js), remote: true do %>
            Edit
          <% end %>
          <%= link_to purok_path(purok[0]), method: :delete do %>
            Delete
          <% end %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%# modal%>
<%= content_for :modal_body do %>
  <%= form_for @purok, url: puroks_path(@purok), method: 'post', html: { autocomplete: :off, class: 'form', id: 'purok-form' } do |f| %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :num %><br />
      <%= f.number_field :num, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :curent_kagawad %><br />
      <%= f.text_field :current_kagawad, class: 'form-control' %>
    </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= f.submit "Save Changes", class: 'btn btn-primary'%>
    </div>
  <% end %>
<% end %>

<%= content_for :modal do %>
  <%= render :partial =>"shared/modal", locals: {modal_title: 'New Purok', modal_id: 'purokModal'} %>
<% end %>

<%= content_for :stylesheet do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></link>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap4.min.css"></link>
<% end %>

<%= content_for :javascript do %>
  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap4.min.js"></script>
  <%= javascript_pack_tag 'puroks/index' %>
<% end %>

app/views/residents/_form.html.erb
<div class="form-group">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :middle_name %><br />
  <%= f.text_field :middle_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :birthdate %><br />
  <%= f.date_field :birthdate, as: :date, value: f.object.to_s, class: 'form-control' %> 

</div>

<div class="form-group">
  <%= f.label :contact_no %><br />
  <%= f.text_field :contact_no, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :purok_id %><br />
  <%= f.select :purok_id, @purok_options, {prompt: 'Select One'}, {class: "form-control"}  %>
</div>

<%= f.submit "Save", class: 'btn btn-primary', style: "margin-top: 20px; width: 80px;"%>

app/views/residents/edit.html.erb
<%= form_for @resident, url: resident_path(@resident), method: 'put', html: { autocomplete: :off, class: 'form col-md-5', id: 'resident-form', style: 'margin: auto;' } do |f| %>
  <%= render partial: 'residents/form', locals: {f: f} %>
<% end %>

app/views/residents/index.html.erb
<a type="button" class="btn btn-primary" href="<%=new_resident_path%>" style="width: 80px; margin-bottom: 20px;">
  New
</a>

<table id="resident-table" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Birthday</th>
      <th>Contact Number</th>
      <th>Purok</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |resident| %>
      <tr>
        <td><%= resident[1]%></td>
        <td><%= resident[2]%></td>
        <td><%= resident[3]%></td>
        <td><%= resident[4]%></td>
        <td>
          <%= link_to edit_resident_path(resident[0]) do %>
            Edit
          <% end %>
          <%= link_to resident_path(resident[0]), method: :delete do %>
            Delete
          <% end %>
        </td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= content_for :stylesheet do %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"></link>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap4.min.css"></link>
<% end %>

<%= content_for :javascript do %>
  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap4.min.js"></script>
  <%= javascript_pack_tag 'residents/index' %>
<% end %>

app/views/residents/new.html.erb
<%= form_for @resident, url: residents_path(@resident), method: 'post', html: { autocomplete: :off, class: 'form col-md-5', id: 'resident-form', style: 'margin: auto;' } do |f| %>
  <%= render partial: 'residents/form', locals: {f: f} %>
<% end %>

app/views/shared/_alert.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= flash[:success] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="<%=modal_id%>" tabindex="-1" role="dialog" aria-labelledby="<%=modal_id%>Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="<%=modal_id%>Label"><%=modal_title%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= yield :modal_body %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <span class="navbar-brand">Barangay Data Management</span>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item <%='active' if controller_name == 'dashboard'%>">
        <a class="nav-link" href=<%=root_path %>>Dashboard <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link <%='active' if controller_name == 'residents'%>" href=<%=residents_path%>>Residents</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <%='active' if controller_name == 'puroks'%>" href=<%=puroks_path%>>Purok</a>
      </li>
    </ul>
    <div class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.email%>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
          Logout
        <% end %>
      </div>
    </div>
  </div>
</nav>